Project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from quiz import views as quizviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     url(r'^$',quizviews.register,name='register'),
    url(r'^quiz/',include('quiz.urls')),    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

quiz/urls.py
from django.conf.urls import url 
from . import views

app_name='quiz'

urlpatterns=[
    url(r'^intro/$',views.intro,name='intro'),
url(r'^(?P<request_id>[0-9]+)/questions/$', views.compete, name='compete'),
url(r'^(?P<request_id>[0-9]+)/move/$', views.move, name='move'),
url(r'^score/$',views.score,name='score'),
url(r'^scoreboard/$',views.scoreboard,name='scoreboard'),
]

quiz/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Question(models.Model):
    question=models.ImageField(upload_to='quiz/img')
    answer=models.TextField()
    name=models.CharField(max_length=100,default='your name')
    timestamp=models.DateTimeField(auto_now_add=True,auto_now=False)
    disappear=models.BooleanField(default=False)
    again=models.BooleanField(default=False)
    def __unicode__(self):
			return self.name 


class User(models.Model):
    name=models.CharField(max_length=60)
    username=models.CharField(max_length=80)
    score=models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.name

quiz/forms.py
from django import forms

from .models import User

class AnswerForm(forms.Form):
	YourAnswer=forms.CharField(required=False)

class UserForm(forms.ModelForm):
	class Meta:
		model=User 
		fields=['name','username']

quiz/views.py
from __future__ import unicode_literals

from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponseRedirect,HttpResponse 

from .models import Question,User
from .forms import AnswerForm,UserForm
from django.urls import reverse


def compete(request,request_id):
    context={}
    form = AnswerForm(request.POST or None)
    question=Question.objects.get(pk=request_id)
    if question:
        if question.disappear==True:
            context={
                    "output":question,
                    "form":form,
                    "answered":'answered',
                }
        else:
            context={
                    "output":question,
                    "form":form,
                }
        if int(request_id)==1:
            if question.disappear==True: 
                    context={
                    "output":question,
                    "form":form,
                    "back":'back',
                    "answered":'answered',
                    }
            else:
                    context={
                    "output":question,
                    "form":form,
                    "back":'back',
                    }
        elif int(request_id)==Question.objects.count():
            if question.disappear==True: 
                context={
                    "output":question,
                    "form":form,
                    "back":'back',
                    "answered":'answered',
                }
            else:
                context={
                    "output":question,
                    "form":form,
                    "front":'front',
                }
            
        
    return render(request,"quiz/game.html",context)

def score(request):

    user=User.objects.order_by('-id')[0]
    questions= Question.objects.all()
    for q in questions:
        q.disappear=False
        q.save()
    context={
        "user":user,
        }

    return render(request,"quiz/score.html",context)

def move(request,request_id):
    question = Question.objects.get(pk=request_id)

    user=User.objects.order_by('-id')[0]
    form=AnswerForm(request.POST or None)
    if form.is_valid():
        if question.answer==form.cleaned_data['YourAnswer']:
            question.disappear=True
            question.save()
            user.score = user.score + 10
            user.save()
    if 'submit' in request.POST:
        return HttpResponseRedirect(reverse('quiz:score')) 
    else:
        if 'next' in request.POST:
            q=int(request_id)+1                   
        elif 'previous' in request.POST:
            q=int(request_id)-1
    return HttpResponseRedirect(reverse('quiz:compete', args=(q,)))

def register(request):
  
    form=UserForm(request.POST or None )
    
    context={
            "form":form,
        }
    if form.is_valid():
        instance=form.save(commit=False)
        if  userexists(form.cleaned_data['username'],form.cleaned_data['name'])==True:
            user=User.objects.all()
            for u in user:
                if u.username==instance.username:
                    context={"user":u,}
                    return render(request,"quiz/score.html",context)
        instance.save()
        return HttpResponseRedirect(reverse('quiz:intro'))
    
    return render(request,"quiz/home.html",context)

def intro(request):
    question=Question.objects.get(pk=1)
    context={'question':question}
    form=UserForm(request.POST or None )
    user=User.objects.order_by('-id')[0]
    user.score=0
    user.save()

    questions= Question.objects.all()
    for q in questions:
        q.disappear=False
        q.save()

    context={
            'question':question,
        }
    
   
    return render(request,"quiz/intro.html",context) 

def scoreboard(request):
    user=User.objects.all()
    user=user.order_by('-score')
    context={
        'user':user,
    }

    return render(request,"quiz/scoreboard.html",context)

def userexists(user_name,full_name):
    users=User.objects.all()
    for u in users:
        if user_name==u.username:
            if full_name==u.name:
                return True
    return False

quiz/templates/quiz/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Quiz</title>
    
    {% include 'quiz/bootstrapstyle.html' %}
    
<script type="text/javascript">
	window.history.forward();
	function noBack() { window.history.forward(); }
</script>
  
  </head>

  <body onload="noBack();" 
	onpageshow="if (event.persisted) noBack();" onunload="">


   {% include 'quiz/navbar.html' %}
    <div class="container">
{% block introdetail %}

{% endblock %}
{% block intro %}
{% endblock %}
{% block question_area %}
      
{% endblock %}
      
 {% block content %}     
     
{% endblock %}






    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
$(window).load(function() {
    $('form').get(0).reset(); //clear form data on page load
});
</script>

  </body>
</html>

quiz/templates/quiz/bootstrapstyle.html
{% load static %}


<!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    

    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

quiz/templates/quiz/game.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block question_area %}
      <div class="row">
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4">
          {% if output %} 
        <img src="{% get_media_prefix %}{{output.question}}" class="img-rounded img-responsive"/>
        {% else %}
        <p class="lead">Sorry :( :( !! No Content Available </p>
        {% endif %}
      </div>
      <div class="col-sm-4">
      </div>
      </div>
{% endblock %}
{% block content %}

     <div class="row">
        <div class="col-sm-4">
        </div>
        <div class="col-sm-4">
      <form class="form-horizontal" method="POST" action="{% url 'quiz:move' output.id %}">{% csrf_token %}
        {%if answered %}
<button class="btn btn-default btn-block">Already Answered</button></a>
{% else %}
<div class="form-group">

{{form|crispy}}
</div>
{% endif %}
</div>
<div class="col-sm-4">
</div>
</div>
<div class="row">
  <div class="col-sm-4">
  </div>
<div class="col-sm-4">
<!--  <input type="submit" value="Submit" class="btn btn-primary pull-right btn-block"/> -->
<!--<a><button class="btn btn-primary btn-block">Previous</button></a>-->
{% if back %}
<input type="submit" value="Previous" class="btn btn-primary btn-block" disabled="disabled" name="previous" />
{% else %}
 <input type="submit" value="Previous" class="btn btn-primary btn-block" name="previous" />
{% endif %}
<input type="submit" value="Submit(Game Over)" class="btn btn-primary btn-block" name="submit" />
{% if front %}
<input type="submit" value="Next" class="btn btn-primary btn-block" disabled="disabled" name="next" />
{% else %}
<input type="submit" value="Next" class="btn btn-primary btn-block" name="next" />
{% endif %}
</div>
<div class="col-sm-4"> 
</div>
</form>
</div>
{% endblock %}

quiz/templates/quiz/home.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block introdetail %}

<div class="starter-template">
        <h1>Quizzers Arena</h1>
        <p class="lead">Use this QuizApp to test your quizzing knowledge.<br> Answer Questions and climb up the leaderboard.</p>
      </div>
{% endblock %}




{% block content %} 
 

<div class="row">
  <div class="col-sm-4">
  </div>
        <div class="col-sm-4 ">
      <form class="form-horizontal" method="POST" action="{% url 'register' %}">{% csrf_token %}
<div class="form-group">
{{form|crispy}}
</div>
</div>
<div class="col-sm-4">
  </div>
  </div>
  <div class="row">
    <div class="col-sm-4">
  </div>
  <div class="col-sm-4">
<input type="submit" value="let's begin " class="btn btn-primary btn-block" />
      </div>
       <div class="col-sm-4">
  </div>
      </form>

</div>
{% endblock %}

quiz/templates/quiz/intro.html
{% extends 'quiz/base.html' %}

{% block intro %}

<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8">
<div class="starter-template lead">
        <h1>Welcome to the Game</h1>
<p> Welcome to the game. You have 10 questions <br>
and you need to answer them correctly without any spelling mistakes. <br>
The more you answer correcty and more you have the chances to lead the score board and claim prizes.
</p>
</div>
</div>
<div class="col-sm-2"></div>

<div class="row">
<div class="col-sm-3"></div>
<div class="col-sm-6">


<a href="{% url 'quiz:compete' question.id %}"><button class="btn btn-primary btn-block">PLAY</button></a>
</div>
<div class="col-sm-9"></div>
</div>
{% endblock %}

quiz/templates/quiz/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Quiz</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'register' %}">Home</a></li>
            <li><a href="{% url 'quiz:scoreboard' %}">ScoreBoard</a></li>
            <li><a href="https://www.linkedin.com/in/sajjan-parida-78740a11b" target="_blank">About</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

quiz/templates/quiz/play.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}


{% block startertemplate %}

<div class="starter-template">
        <h1>Quizzers Arena</h1>
        <p class="lead">Use this QuizApp to test your quizzing knowledge.<br> Answer Questions and climb up the leaderboard.</p>
      </div>
{% endblock %}

quiz/templates/quiz/score.html
{% extends 'quiz/base.html' %}

{% block intro %}

<div class="row">
<div class="col-sm-2"></div>
<div class="col-sm-8">
<div class="starter-template lead">
        <h1>Quiz Over :) </h1>
<p> {{user.name}} has score <strong>{{user.score}}</strong></p>
<p>Want to take the Quiz Again</p>
<a href="{% url 'quiz:intro'  %}"><button class="btn btn-primary btn-block">PLAY</button></a>
</div>
<div class="col-sm-2"></div>

<div class="row">
<div class="col-sm-3"></div>
<div class="col-sm-9"></div>
</div>
{% endblock %}

quiz/templates/quiz/scoreboard.html
{% extends 'quiz/base.html' %}
{% load static %}

{% block intro %}
<div class="container">
    <div class="starter-template lead">
        <table class="table table-bordered"> 
        <thead>
            <tr>
                <th>Rank</th>
                <th>Name</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
        </thead>
        <tbody>
            {% for q in user %}
            <tr>
            <td>{{forloop.counter}}</td>
            <td>{{q.name}}</td>
            <td>{{q.username}}</td>
            <td>{{q.score}}</td>
            </tr>
            {% endfor %}
        </tbody>
        </table>
    </div>
</div>
{% endblock %}